# Generated by Django 5.0.7 on 2024-08-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rand',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
