# Generated by Django 5.0.7 on 2024-08-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_rand_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='rand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rand',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
