# Generated by Django 5.0.7 on 2024-08-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_rand_is_active_alter_rand_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_data', models.TextField()),
                ('vector', models.BinaryField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rand',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rand',
            name='is_staff',
        ),
    ]
