# Generated by Django 5.0.7 on 2024-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_studentinfo_remove_rand_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
