# Generated by Django 5.0.7 on 2024-08-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_studentinfo_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='semester',
        ),
    ]
