# Generated by Django 5.0.7 on 2024-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_remove_studentinfo_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
